name: '@thnetii/microsoft-odata-csdl-github-actions-commit-push'
author: thnetii
description: ''
inputs:
  branch-name:
    required: true
    description: ''
  commit-message:
    required: true
    description: ''
runs:
  using: composite
  steps:
    - id: commit-push
      uses: actions/github-script@v6.4.1
      with:
        script: |
          require(process.env['GITHUB_ACTION_PATH'])(
            {
              github, context, core, exec,
              inputs: JSON.parse(process.env['ACTION_INPUTS_JSON']),
            }
          );
      env:
        ACTION_INPUTS_JSON: ${{ toJson(inputs) }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
outputs:
  committed:
    description: ''
    value: ${{ steps.commit-push.outputs.committed }}
