name: '@thnetii/microsoft-odata-csdl-github-actions-spo-bearer-challenge'
author: thnetii
description: ''
inputs:
  sharepoint-web-url:
    required: true
    description: ''
runs:
  using: node16
  main: action.js
