name: '@thnetii/microsoft-odata-csdl-github-actions-merge-branch'
author: thnetii
description: ''
inputs:
  branch-name:
    required: true
    description: ''
  commit-message:
    required: false
    description: ''
runs:
  using: composite
  steps:
    - id: merge-branch
      uses: actions/github-script@v6.4.1
      with:
        script: |
          require(process.env['GITHUB_ACTION_PATH'])(
            {
              github, context, core,
              inputs: JSON.parse(process.env['ACTION_INPUTS_JSON']),
            }
          );
      env:
        ACTION_INPUTS_JSON: ${{ toJson(inputs) }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
