name: '@thnetii/microsoft-odata-csdl-github-actions-powerplatform-api-connector-download'
author: thnetii
description: ''
inputs:
  access-token:
    required: true
    description: ''
  api-version:
    required: false
    description: ''
  api-endpoint:
    required: false
    default: 'https://api.flow.microsoft.com'
    description: ''
  environment:
    default: '~default'
    description: ''
  api-connector:
    required: true
    description: ''
runs:
  using: node20
  main: action.js
outputs:
  properties:
    description: ''
