on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - csdl
      - powerplatform
  schedule:
    - cron: '04 7 * * *'
      # Trigger every day at 07:04
permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  odata_csdl:
    name: Download Microsoft Graph OData CSDL
    runs-on: ubuntu-latest
    steps:
      - id: rate-limit
        name: Check GitHub API rate limit
        uses: thnetii/.github/actions/gh-actions-ratelimit-check@main
      - name: Wait until GitHub API rate limit reset
        if: fromJson(steps.rate-limit.outputs.remaining) < 20
        uses: thnetii/.github/actions/gh-actions-sleep-until@main
        with:
          datetime: ${{ steps.rate-limit.outputs.reset }}
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 180
          submodules: true
      - name: Git configure comitter identity
        uses: thnetii/.github/actions/git-user-config@main
      - id: checkout-pr-branch
        name: Swich to new branch for possible PR
        uses: thnetii/.github/actions/create-rebase-pr-branch@main
        with:
          branch-name: csdl-fetcher/msgraph
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - id: npm-clean-install-actions
        name: Install NPM package dependencies for Github actions
        uses: thnetii/.github/actions/gh-actions-npm@main
        with:
          arguments: |
            clean-install
            --workspace=@thnetii/microsoft-odata-csdl-github-actions-msgraph-csdl-download
            --omit=dev
            --install-links
            --no-audit
            --no-fund
      - id: msidp-workflow-auth
        name: Authenticate GitHub Actions Workflow
        uses: thnetii/.github/actions/ms-idp-workflow-run-auth@main
        with:
          tenant-id: ${{ secrets.MSIDP_TENANTID }}
          client-id: ${{ secrets.MSIDP_CLIENTID }}
          resource: https://graph.microsoft.com
      - id: download-v1_0-csdl
        name: Download Microsoft Graph v1.0 CSDL in XML format
        uses: ./.github/actions/msgraph-csdl-download
        with:
          access-token: ${{ steps.msidp-workflow-auth.outputs.access-token }}
          api-version: v1.0
          file-path: csdl/microsoft-graph-v1.0.csdl.xml
      - id: download-beta-csdl
        name: Download Microsoft Graph beta CSDL in XML format
        uses: ./.github/actions/msgraph-csdl-download
        with:
          access-token: ${{ steps.msidp-workflow-auth.outputs.access-token }}
          api-version: beta
          file-path: csdl/microsoft-graph-beta.csdl.xml
      - id: commit
        name: Commit and push (if any changes)
        uses: ./.github/actions/commit-push
        with:
          branch-name: csdl-fetcher/msgraph
          commit-message: Microsoft Graph OData CSDL
      - id: merge
        name: Merge into ${{ github.ref || github.sha }}
        if: fromJSON(steps.commit.outputs.committed)
        uses: ./.github/actions/merge-branch
        with:
          branch-name: csdl-fetcher/msgraph
