name: Node.js lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  tsc:
    name: TypeScript check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: thnetii/gh-actions/src/add-matcher-npm@main
      - name: npm install
        run: npm ci -workspaces --include-workspace-root
        working-directory: .github/actions
      - name: npm run lint:tsc
        uses: thnetii/gh-actions/src/gh-actions-tsc@main
        with:
          working-directory: .github/actions
          arguments: |
            --noEmit
            -p
            ./jsconfig.json

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: thnetii/gh-actions/src/add-matcher-npm@main
      - name: npm install
        run: npm ci -workspaces --include-workspace-root
        working-directory: .github/actions
      - name: npm run lint:eslint
        run: npm run lint:eslint
        working-directory: .github/actions
