on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: '18 5 * * *'
      # Trigger every day at 05:18
permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  powerplatform-apis:
    name: Download Power Platform API Connectors
    runs-on: ubuntu-latest
    env:
      api-version: '2023-05-01'
      environment: '~default'
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 180
          submodules: true
      - uses: actions/setup-node@v3
      - id: npm-clean-install-actions
        name: Install NPM package dependencies for Github actions
        uses: thnetii/.github/actions/gh-actions-npm@main
        with:
          arguments: |
            clean-install
            --workspace=@thnetii/microsoft-odata-csdl-github-actions-powerplatform-apis-collection-download
            --workspace=@thnetii/microsoft-odata-csdl-github-actions-powerplatform-apis-collection-processor
            --omit=dev
            --install-links
            --no-audit
            --no-fund
      - id: msidp-workflow-auth
        name: Authenticate GitHub Actions Workflow
        uses: thnetii/.github/actions/ms-idp-workflow-run-auth@main
        with:
          tenant-id: ${{ secrets.MSIDP_TENANTID }}
          client-id: ${{ secrets.MSIDP_CLIENTID }}
          resource: https://service.flow.microsoft.com/
      - id: get-api-connectors
        name: Get Power Platform API Connectors
        uses: ./.github/actions/powerplatform-apis-collection-download
        with:
          access-token: ${{ steps.msidp-workflow-auth.outputs.access-token }}
          api-version: ${{ env.api-version }}
          environment: ${{ env.environment }}
      - id: process-api-connectors
        name: Process Power Platform API Connectors
        uses: ./.github/actions/powerplatform-apis-collection-processor
        with:
          access-token: ${{ steps.msidp-workflow-auth.outputs.access-token }}
          api-endpoint: ${{ steps.get-api-connectors.outputs.api-endpoint }}
          environment: ${{ steps.get-api-connectors.outputs.environment }}
          api-connector-names: ${{ steps.get-api-connectors.outputs.api-connector-names }}
          api-version: ${{ env.api-version }}
