on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: '48 6 * * *'
      # Trigger every day at 06:48
permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

concurrency:
  group: ${{ github.workflow }}

jobs:
  odata_csdl:
    name: Download SharePoint OData CSDL
    runs-on: ubuntu-latest
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - id: determineWorkflow
        name: Get current workflow id
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/determineWorkflow')
            await script({github, context, core})
      - name: Git configure comitter identity
        shell: bash
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
      - id: checkoutPrBranch
        name: Swich to new branch for possible PR
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/checkout-pr-branch')
            await script({github, context, core, exec}, '${{ steps.determineWorkflow.outputs.branch_name }}')
      - id: challenge
        name: Invoke OAuth2 challenge
        shell: pwsh
        env:
          SHAREPOINT_WEBURL: ${{ secrets.SHAREPOINT_WEBURL }}
        run: './scripts/sharepoint-online-bearer-challenge.ps1'
      - id: getAuthMetadata
        name: Get Authorization Instance Metadata
        shell: pwsh
        env:
          SHAREPOINT_AUTH_INSTANCE: ${{ steps.challenge.outputs.auth_instance }}
          SHAREPOINT_REALM: ${{ steps.challenge.outputs.realm }}
        run: './scripts/sharepoint-online-auth-metadata.ps1'
      - id: tokenIssuance
        name: Get SharePoint Access Token
        shell: pwsh
        env:
          SHAREPOINT_WEBURL: ${{ secrets.SHAREPOINT_WEBURL }}
          SHAREPOINT_CLIENTID: ${{ secrets.SHAREPOINT_CLIENTID }}
          SHAREPOINT_CLIENTSECRET: ${{ secrets.SHAREPOINT_CLIENTSECRET }}
          SHAREPOINT_REALM: ${{ steps.challenge.outputs.realm }}
          SHAREPOINT_RESOURCEID: ${{ steps.challenge.outputs.resource_id }}
          SHAREPOINT_TOKENENDPOINT: ${{ steps.getAuthMetadata.outputs.token_endpoint }}
        run: |
          [void](./scripts/sharepoint-online-access-token.ps1)
      - id: downloadCsdl_OData_v4_0
        name: Download CSDL in XML Format
        shell: pwsh
        env:
          SHAREPOINT_WEBURL: ${{ secrets.SHAREPOINT_WEBURL }}
          SHAREPOINT_ACCESSTOKEN: ${{ steps.tokenIssuance.outputs.access_token }}
        run: |
          ./scripts/sharepoint-online-download-csdl-xml.ps1 `
            -OutFile ./sharepoint-odata-v4_0.csdl.xml -ODataVersion "4.0" `
            -EdmNamespace  "http://docs.oasis-open.org/odata/ns/edm" `
            -EdmxNamespace "http://docs.oasis-open.org/odata/ns/edmx"
      - id: downloadCsdl_v2_0_OData_v4_01
        name: Download CSDL in XML Format
        shell: pwsh
        env:
          SHAREPOINT_WEBURL: ${{ secrets.SHAREPOINT_WEBURL }}
          SHAREPOINT_ACCESSTOKEN: ${{ steps.tokenIssuance.outputs.access_token }}
        run: |
          ./scripts/sharepoint-online-download-vNext-csdl-xml.ps1 `
            -ApiVersion "v2.0" -ODataVersion "4.01" `
            -OutFile ./sharepoint-v2.0-odata-v4_01.csdl.xml
      - id: downloadCsdl_v2_1_OData_v4_01
        name: Download CSDL in XML Format
        shell: pwsh
        env:
          SHAREPOINT_WEBURL: ${{ secrets.SHAREPOINT_WEBURL }}
          SHAREPOINT_ACCESSTOKEN: ${{ steps.tokenIssuance.outputs.access_token }}
        run: |
          ./scripts/sharepoint-online-download-vNext-csdl-xml.ps1 `
            -ApiVersion "v2.1" -ODataVersion "4.01" `
            -OutFile ./sharepoint-v2.1-odata-v4_01.csdl.xml
      - id: createPr
        name: Commit and create/update PR (if any changes)
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/commit-updatecreate-pr')
            const branch_name = '${{ steps.determineWorkflow.outputs.branch_name }}'
            const git_commit_message = 'SharePoint OData CSDL, Microsoft SharePoint Team Service version ${{ steps.challenge.outputs.sharepoint_version }}'
            const pr_title = 'Update SharePoint OData CSDL'
            const pr_body = `Automatic download of SharePoint API OData CSDL.

            Microsoft SharePoint Team Services: \`${{ steps.challenge.outputs.sharepoint_version }}\`

            Includes:
            - SharePoint OData API for OData-Version 4.0 clients
            - SharePoint v2.0 OData API for OData-Version 4.01 clients
            - SharePoint v2.1 OData API for OData-Version 4.01 clients`
            await script(
              {github, context, core, exec},
              branch_name,
              git_commit_message,
              pr_title,
              pr_body
            )
      - name: Add Labels to Pull Request
        if: ${{ format('{0}', steps.createPr.outputs.prNumber) != '' }}
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/add-labels-pr')
            await script(
              {github, context},
              ${{ steps.createPr.outputs.prNumber }},
              ['csdl-update', 'sharepoint', 'odata-v4']
            )
